version: "3"
services:
  web:
    image: "kevoooo/twitchfarm-web:latest"
    ports:
      - "80:80"
  database:
    image: "kevoooo/twitchfarm-db:latest"
    volumes:
      - "twitchfarm:/var/lib/mysql"
    ports:
      - "3306:3306"
  chromedriver:
    image: selenium/standalone-chrome:4.0.0-rc-2-prerelease-20210908
    ports:
      - "4444:4444"
      - "7900:7900"
    hostname: chromedriver
    shm_size: 2g
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080

volumes:
  twitchfarm:
  chrome-data:
