version: "3"
services:
  web:
    image: "kevoooo/twitchfarm-web:latest"
    ports:
      - "80:80"
  database:
    image: "kevoooo/twitchfarm-db:latest"
    volumes:
      - "twitchfarm:/var/lib/mysql"
    ports:
      - "3306:3306"
  runner:
    image: "kevoooo/twitchfarm-runner:latest"
    entrypoint: python3 /py-scripts/main.py
    healthcheck:
        test: python3 /py-scripts/main.py
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      - USER=kevooo98
      - PASS=H3nni33!!TWITCH
      - 2FA_KEY=OPC4T533MRSXH6QEGM4NEW6OMSEVNTI7TVRQUPNAGEOVRLFXB43A
    volumes:
      - "chrome-data:/saves/google-chrome"
volumes:
  twitchfarm:
  chrome-data:
