version: "3"
services:
  web:
    build: ./Web/
    ports:
      - "80:80"
  database:
    build: ./Database/
    volumes:
      - "twitchfarm:/var/lib/mysql"
    ports:
      - "3306:3306"
  chromedriver:
    image: selenium/standalone-chrome:4.0.0-rc-2-prerelease-20210908
    ports:
      - "4444:4444"
      - "7900:7900"
    hostname: chromedriver
    shm_size: 2g
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
  runner:
    build: ./Runner/
    entrypoint: bash -c "sleep 10 && python3 /py-scripts/main.py"
    healthcheck:
        test:  ["CMD", "curl", "-f", "http://chromedriver:4444"]
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      - USER=
      - PASS=
      - 2FA_KEY=
    depends_on:
      - chromedriver
volumes:
  twitchfarm:
  chrome-data:
